### ISSUE TITLE
Calendar sync or remind

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#107]
refer to luma‘s email remind

**Comment by eggyji** [comment]
"Basically for people to see the activities in their calendar they can link it to their calendar. Therefore we could have virtual and in person calendars for virtual and in person activities"
could be a tag of inperson or virtual?

**Comment by mjmoneyiris** [comment]
Email 格式
title： [活动标题]
content：（线下地址）+（线上地址）
time：12:00-14:00
