### ISSUE TITLE
[Edge City] Edge City Requirements

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#116]
edge city 需求：

1. ✅独立子域名
2. ✅zupass 集成，需要 ticket id
3. ✅send a badge 文案改成 set a POAP badge for attendees
4. ✅加上calendar view菜单按钮
5. ✅点击 venue 去往 sola map view
6. ✅除了list view有tag 作为filter之外， timeline view/ calendar view/ schedule也需要
7. calendar view 上面的跨天的theme占据的空间可以小一点
8. ✅calendar和timline需要根据不同的 tag有颜色的区分，可以根据tag筛选
9. ✅进入group页之后需要有个方式回到event页，同理，发完badge之后也需要回到event页，最好是编辑中的event
10. ✅在list视图 除了有不同的tag来筛选之外 还可以用“当天”“本周”“本月活动来筛选” 
11. ✅URL只保留一个 external or online URL
12. ✅类似google calendar 直接在日历页面create event
13. ✅选择开始时间后，最好结束时间就自动跳成开始时间之后的半小时（类似腾讯会议 zoom会议）
14. ✅Co-host 最好可以也填写还没有注册sola的人的名字（然后之后还能改co-host 把注册后的人链接进来）
15. ✅ Create a badge 后会到profile和badge页面然后就回不到event页面了 也没有回到create中的event页面
16. 需要让host可以选择需不需要av（舞台控制blabla技术，能不能允许别人带食物进来）实际上是一些只给owner 和manager看到的信息（这个真的太细了 但是Janine觉得很重要）
17. ✅有一些闭门活动需要隐藏（是不是需要一个list but no public，然后发送链接邀请才可以参加活动）
18. ✅Edge City 独立域名页面导航栏定制化 Edge City logo x Social Layer
19. ✅还有一处语法错误：When an event participant check[s] in. —> 第三人称单数 s
20. 根据用户票种决定可以展示/报名的活动
21. ✅文案：event-site -> venues

**Comment by eggyji** [comment]
还有一处语法错误：When an event participant check[s] in. —> 第三人称单数 s

**Comment by eggyji** [comment]
✅ Edge Esmeralda 独立域名页面导航栏定制化 Edge Esmeralda logo x Social Layer

**Comment by mjmoneyiris** [comment]
涉及到设计：
9. Group 页增加跳转到 event page 
17. 闭门活动隐藏
其他：Manager 添加入口需要开放其他人、邀请member的入口放到 setting 里面

**Comment by qieman** [comment]
> 10\. 在list视图 除了有不同的tag来筛选之外 还可以用“当天”“本周”“本月活动来筛选”
> 12\. 类似google calendar 直接在日历页面create event

这两点需要@mjmoneyiris 设计支持

**Comment by eggyji** [comment]
notion中新增需求：
1. “profile页”中badge旁边的几个按钮不在同级，不make sense且太过于crypto focus，资产里面不需要有seedao 这种专属于其他社区的模块。建议
“The options above of badge, sending, groups, assets doesn’t make that much sense and no one really needs to see SeeDAO on there. The above is also very crypto focused and ideally it’s more general”
<img width="1066" alt="Untitled" src="https://github.com/sociallayer-im/product-management/assets/27666814/bcd7d899-5215-4eb1-a555-4572355b73e2">

2. 编辑profile中可以连接的其他social media加上farcaster
<img width="702" alt="Untitled (1)" src="https://github.com/sociallayer-im/product-management/assets/27666814/43303d27-b542-445d-88a7-a6dff58adc8f">

**Comment by eggyji** [comment]
✅ janine 是manager ，但是她发布的活动在她的my event里面显示 pending
✅ 然后她也有pending request 这个tab，但是她pending request这里看不到自己被pending的活动
https://www.loom.com/share/fc9c091da6fe4e29b75f35d08ed7a525?sid=47947726-d023-4319-8341-dd1b911de8ee

**Comment by eggyji** [comment]
🔥 需要让不是edge city 对member 无法看到event 具体的venue... 其实就是这个group需要是一个member gated的group，只有member可见.... 主要的担心点是会有不是member的人冲进场地里 然后很多人
✅ 在日历中，发生在不同场地的活动用不同颜色表示（和tag又不一样了....），在后台设置中可以选择不同的场地的用不同的颜色表示
✅（这条需求先不管吧，他们现在想要labweek的那种格式）因为一天会同时发生很多场活动，因此需要让calendar view里面的格子变大一些，或者default view是day 而不是现在的weeek（wtf？）
https://www.loom.com/share/9314234ce980438f8d2cc5f847fef333?sid=9cafe701-4f9e-4ddc-aa0a-8357513a461f

**Comment by qieman** [comment]
> 1. janine 是manager ，但是她发布的活动在她的my event里面显示 pending
> 2. 然后她也有pending request 这个tab，但是她pending request这里看不到自己被pending的活动
>    https://www.loom.com/share/fc9c091da6fe4e29b75f35d08ed7a525?sid=47947726-d023-4319-8341-dd1b911de8ee

@EggyJ 查了一下数据，用户发布视频的时候还不是group 的成员，稍后才成为manager。这个group 的event 发布权限是member, 所以之前发布的活动都是pending

**Comment by eggyji** [comment]
**p1:**
1. ✅不同周 和 不同 tag 的schedule需要用不同的链接地址：week1: https://edgecity.sola.day/event/edgecity/schedule/1
2. ✅切换不同的view的时候保持在同样的一周
3. ✅Co-host 要有修改event details的权限，Co-host 可以用email邀请，在cohost用email登录并注册sola id后，这位cohost就能修改event details
4. ✅Schedule view设置为默认view

**p2:**
1. ✅一些比较重要的空间，如果有人需要预约使用的话，需要申请，经manager/owner的同意，才能在这个venue host活动，而其他一些空间则不用: https://docs.google.com/spreadsheets/d/1Sxs4eaef4hdkjo83LjobHT-4oBaUWTNJDdmphSqNnb8/edit#gid=0
2. ✅有一个bug: 作为owner 发布活动的时候弹出他发布的活动需要被审核，虽然还是能成功发布，但是会被弹窗
3. ✅[Designed] 空间使用的细节用event note不够，需要有一些选项给host来选 
        a. Seating arrangement style: stadium, theater, workshop, single table + chairs
        b. AV needed: presentation screen, microphone, speakers

4. ✅schedule的时间从现在的周三到周四改成周一到周日和calendar view一样

5. ✅calendar view的卡片点进去可以查看event detail
6. ✅时区改成PST
7. ✅calendar view里面最上面的一条条在滚动后需要隐藏起来一些
8. ✅把schedule view设置成default one

9. ✅对所有没有相应时间段门票的用户隐藏活动event venue和RSVP

10. ✅[Designed] Speaker 显示的位置（创建完成后查看event detail的时候）需要和co-host显示的位置分开
11. ✅Speaker和 cohost的填写位置需要放回填写host的地方之后 （填写co-host和speaker的时候需要提示可以直接填写名字， 填写一串名字后显示的时候需要一个一个分开显示，默认头像不要用水母头像，要可以上传嘉宾的照片，嘉宾名字要可以空格写全名）


12. ✅tag的颜色用edge esmeralda的色盘: https://www.figma.com/design/m2cTwg08VfduVdxa2JJs9Y/Edge-City?node-id=1451%3A5844&t=iWWBNncjdQgn7kgA-1
✅ edgecity.sola.day 改成edgeesmeralda.sola.day
✅ logo要改
13. 现在已经安排了很多活动，需要有一次性上传的操作https://docs.google.com/spreadsheets/d/1pE9k1_AH_AAi067JJOxVDDYWgi2i1GrA6kpfzGZgzBI/edit#gid=1715003595 

14. 用labweek的方式一个为期两天的活动具体的session在这个两天活动点开的详情里面：https://24.labweek.io/24-pg/schedule/calendar#funding-the-commons 
15. ✅profile/group 增加 facaster 字段
16. ✅zupass 登录加上描述
17. ✅日历支持多个tag 筛选
18. ✅invite 描述使用nickname
19. ✅添加 Labweek logo, 6月10-16日显示logo
20. ✅map 卡片加上时间
21. ✅location 隐藏仅仅适用于edgecity
22. ✅venue 编辑页增加分割线 
23. ✅facaster 跳转

**Comment by eggyji** [comment]
需要把edgecity改成 edge esmeralda的地方还有：
![2024-05-16 18 02 18](https://github.com/sociallayer-im/product-management/assets/27666814/028ed171-d573-43ef-9633-7f13d6b5d7fe)
![2024-05-16 18 02 27](https://github.com/sociallayer-im/product-management/assets/27666814/05440cc5-684c-4c68-9b8f-1c420a11efa8)
![2024-05-16 18 02 32](https://github.com/sociallayer-im/product-management/assets/27666814/48637b02-9cbb-4679-b9ac-51ea8f19f259)

**Comment by eggyji** [comment]
- ✅创建活动的时候因为venue很多，如果能把一些在当前时间无法选择的地点标记灰色（或隐藏）就方便很多，否则得一个一个试哈哈哈
- ✅把invite a cohost 的提示语改成：Enter your cohost’s name, domain, or wallet address
<img width="684" alt="Untitled (2)" src="https://github.com/sociallayer-im/product-management/assets/27666814/0a7bb7a7-ea39-48af-8067-61b4a45acaa3">

**Comment by eggyji** [comment]
bug: 发送manager邀请接受后还是会一直弹出邀请
![2024-05-25 00 09 28](https://github.com/sociallayer-im/product-management/assets/27666814/3ddfdf7a-153a-4cd9-a1f8-e1b909ffdff4)

✅bug：longevity标签改过后，错误的版本还会存在在页面上
![2024-05-25 00 09 11](https://github.com/sociallayer-im/product-management/assets/27666814/3865d7a9-210e-474c-8f2c-7cdd8746f9ac)

**Comment by eggyji** [comment]
这个需求我觉得也挺thoughtful，不同的活动类型，talk，workshop或recreation有个区分: On the week-view, can we have a quick visual way of identifying which events are talks, which are workshops and which are recreation. Color coding a possibility?

**Comment by eggyji** [comment]
默认背景如果好改的话：
![Frame 1](https://github.com/sociallayer-im/product-management/assets/27666814/723e6d2b-aecb-4c65-a099-977be3e448af)
![Frame 2](https://github.com/sociallayer-im/product-management/assets/27666814/3a18633c-f4d4-499c-8ef7-700de68dce38)
