### ISSUE TITLE
Zupass Integration

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#122]
### 

- **Event Feed in Zupass**: Convert the list of events from Social Layer into a folder and add it as a feed to Zupass.
     https://zupass-feed-server-sage.vercel.app/edgecity/feeds **现在这个有bug**
- **Event Check-in and Badge Empowerment**: Automatically generate proofs for badge empowerment based on user check-ins at events, including proofs of consecutive participation at the same location, or under the same tag.
    🔄 Proof in Zupass to earn $zucash and sola badge 
    1. topic badge (for people who checkin event in certain topic)
    2. challenge badge (for people who checkin cold plunge or some local restaurant/ market)
    3. venue badge (for people checkin in some event venuew)
- **Special Event for Badge Holder**: User can only RSVP some special events when they hold some special badge. (need to design the playbook)

**Comment by eggyji** [comment]
Edge City 的不同票的持有者有不同的权限（只能报名票所包含的时间内的活动）

**Comment by jiangplus** [comment]
权限已经在另一个issue里面了
https://github.com/sociallayer-im/product-management/issues/110
