### ISSUE TITLE
[Edge City]When the user changes their personal nickname and group nickname, their photo, it does not refresh promptly on the host/cohost display for all event

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#131]
![2024-05-30 10 36 41](https://github.com/sociallayer-im/product-management/assets/27666814/41190131-dc0f-4ffc-95ce-33b2b7869406)
![2024-05-30 10 36 47](https://github.com/sociallayer-im/product-management/assets/27666814/957f643f-3f42-4a4e-923f-eff3357818f6)

**Comment by eggyji** [comment]
<img width="721" alt="photo" src="https://github.com/sociallayer-im/product-management/assets/27666814/1918452e-aa4d-4de6-9d5a-37dacefa5d07">

**Comment by eggyji** [comment]
具体的需要呈现个人/组织 identity的地方：
1. Event Detail中的 Host：希望尽可能在用户修改nickname和头像后，能够在这个地方显示出来
<img width="1075" alt="Screenshot 2024-06-02 at 23 26 14" src="https://github.com/sociallayer-im/product-management/assets/27666814/b552a11f-1d02-4641-9561-f9f12d36f3b6">
2. 报名活动中的参与者信息：作为一个社交应用，能够在event中查看其他人的报名情况（看看自己的朋友是不是有报名等等）是一个比较好的状态，因此希望尽可能在这里也显示nickname而不是domain
<img width="700" alt="Screenshot 2024-06-03 at 00 02 54" src="https://github.com/sociallayer-im/product-management/assets/27666814/cfa450fd-9bad-43a6-b3ab-1b70d706d633">
