### ISSUE TITLE
[Edge City] Protocol Labs link button

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#135]
improve the landing page of social layer to show a few jump points to other websites/pages? For these pages specifically - LabWeek schedule view and the EE landing page. Can we add a button to the IRL Gatherings page? Button Label = "View Attendees"

点击"View Attendees"按钮后跳转 https://directory.plnetwork.io/irl/ee-lwfb 

![2024-05-30 10 59 19](https://github.com/sociallayer-im/product-management/assets/27666814/45a2682f-6051-4451-8589-7dfc3ec6e317)

**Comment by eggyji** [comment]
Added the "View Attendees" button on the homepage of [https://edgeesmeralda.sola.day](https://edgeesmeralda.sola.day)
