### ISSUE TITLE
[Edge City] Even with a ticket for the corresponding time, some activities are still available for RSVP while others are not.

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#140]
"For #1 I'm seeing weird inconsistencies where I can register for some events during weekend 2 (e.g. Replacing Aging https://edgeesmeralda.sola.day/event/detail/6334), but not others on the same weekend (e.g. Edge AGI forum https://edgeesmeralda.sola.day/event/detail/6900 or AI alignment program https://edgeesmeralda.sola.day/event/detail/6332). Initially I thought it was because you can't have concurrent registrations, but I was able to register for concurrent events."

I checked Lemonade and they do have the ticket for weekend 2 (shawn.dimantha@gmail.com), do you know why they wouldn't be able to see the RSVP button?

**Comment by eggyji** [comment]
This issue cannot be reproduced and requires further observation.

**Comment by kevzhai** [comment]
From another attendee:

The attendee `jcjcjc` was able to RSVP to one of the events they couldn't before: https://edgeesmeralda.sola.day/event/detail/6900 (Edge AGI Forum, Jun 16)

But they are still unable to see the RSVP button for the remaining:

* https://edgeesmeralda.sola.day/event/detail/7210 (Field Building I Biotech for Longevity, Jun 14)
* https://edgeesmeralda.sola.day/event/detail/6872 (Longevity Fund w/Laura D Carte Blanche, Jun 14)
* https://edgeesmeralda.sola.day/event/detail/6901 (Edge dinner, Jun 16)

Their ticket is for Weekend 2 (June 14-16) so all the events should be valid.

**Comment by kevzhai** [comment]
peter@approx.vc (`peterzhegin` on Social Layer) can't see the RSVP button for events he should have access too (Week 2 ticket)

![image](https://github.com/sociallayer-im/product-management/assets/13242093/8812b603-686e-4df1-ad54-ea5ae0681548)
