### ISSUE TITLE
[Edge City] The boardcast time of the events of the day should at morning or the evening before the day

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#141]

**Comment by Cupnfish** [comment]
https://github.com/sociallayer-im/sola-bot/commit/ffeb9ee24e0ac9e0eb1962b8bd96025a0e989050
I have already attempted to fix it and have submitted the deployment to the environment. You can test it out and provide me with timely feedback on the test results.

**Comment by Cupnfish** [comment]
https://github.com/sociallayer-im/sola-bot/commit/aa2307c26d7a2ac15625ec8e6c1e645425fcf5e1
I have submitted the new fixes. Please provide timely feedback on the test results once they are available.
