### ISSUE TITLE
[Edge City] Manually approve guests who RSVP

### ISSUE THREAD

**Issue by kevzhai** [sociallayer-im/product-management#148]
From attendee:

"How do I approve attendees for an event I'm hosting? 

My event page says the attendees applied, but is there a way to mark someone as approved so it shows as approved rather than just applied?"

**Comment by kevzhai** [comment]
"Great thanks. Alternatively, the wording could be changed from “Applied” to “Attending” so people know that after they rsvp they’re set"

**Comment by kevzhai** [comment]
Another attendee:

"What is the guarantee of a RSVP? Right now I see "Applied" status for the events I've RSVPd for, does that mean I have to be approved by the event organizer? Unclear because on the event page it says I'm registered, but on my profile "My Events" page registered tab it says "Applied" in red in the summary view of all events."

**Comment by jiangplus** [comment]
There is no need to approve. We will change the wording on the app.
