### ISSUE TITLE
[Edge City] Click on label on event page should take you to filtered event list

### ISSUE THREAD

**Issue by kevzhai** [sociallayer-im/product-management#173]
From attendee: Suppose you're in a /event/detail page like https://edgeesmeralda.sola.day/event/detail/6334

Below the title it would be nice if the tags like "Health Longevity & Bio" were clickable.

If I click, I would then be brought to the list of such events: https://edgeesmeralda.sola.day/event/edgeesmeralda/schedule?date=2024-06-10&tag=Health%20Longevity%20%26%20Bio

**Comment by eggyji** [comment]
这个目前也还是没有实现

**Comment by eggyji** [comment]
和之前提的一个重复了，这个先关了
