### ISSUE TITLE
Need easy way to switch between group and event management as Group Manager

### ISSUE THREAD

**Issue by vvorski** [sociallayer-im/product-management#182]
There is no easy way to switch between:
https://beta.sola.day/event/the-gathering?tab=past
and 
https://beta.sola.day/group/the-gathering?tab=0

I would expect the "event" button on group page to take me to the event, but it doesn't work currently
![image](https://github.com/sociallayer-im/product-management/assets/1789426/81740b19-6b87-4403-9a5b-306f57cc3a6e)

**Comment by jiangplus** [comment]
因为这里很让人困惑，所以还是移除 group 页面的 event tab；
同时需要增加一个更好的跳转到 event 页的入口。
@qieman @mjmoneyiris

**Comment by mjmoneyiris** [comment]
https://www.figma.com/design/SJQGvLw5RuN2xadroJ1i7j/%E6%B4%BB%E5%8A%A8%E5%85%A5%E5%8F%A3web?node-id=6912-16037&t=BqVCV2W5yQCGx6eC-4
增加了一个固定入口在 event tab 下方
<img width="696" alt="image" src="https://github.com/sociallayer-im/product-management/assets/163380744/8cc532fb-bf92-4534-acc2-e8a4683fb9fa">

**Comment by mjmoneyiris** [comment]
<img width="806" alt="image" src="https://github.com/sociallayer-im/product-management/assets/163380744/b193e1fb-7330-4e0e-9fea-18e2a15a3754">
这里附上 luma 的 profile 作为参考，luma 的活动 host profile 是有 hosting 列表的，所以建议我们还是保留 event list
