### ISSUE TITLE
[Juan]Add a feedback buttion on homepage

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#185]
Add a feedback button visible on mobile page, that pops up a field + submit, so we can reduce friction to give you fast feedback & improve the product

**Comment by mjmoneyiris** [comment]
https://www.figma.com/design/SJQGvLw5RuN2xadroJ1i7j/%E6%B4%BB%E5%8A%A8%E5%85%A5%E5%8F%A3web?node-id=7368-31981 设计稿已完成

**Comment by mjmoneyiris** [comment]
需要确认一下我们接收反馈的官方邮箱是什么 @jiangplus @EggyJ

**Comment by eggyji** [comment]
hi@sola.day ？

**Comment by mjmoneyiris** [comment]
@jiangplus 这个已经完成了，所以我 remove 了 d1 标签

**Comment by jiangplus** [comment]
加上两个按钮吧，一个是电子邮箱联系，一个是 tally 表单

**Comment by jiangplus** [comment]
https://tally.so/r/w8ePXO

**Comment by nicosxt** [comment]
@.  Oi
