### ISSUE TITLE
[Juan]Fix browser back button

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#186]
- The back button still doesn’t work well. 
- I try going into events and then back button, and it usually drops me in a different page (eg wrong day - start of the week instead of the day I was on). 
- Every action should properly push onto the history stack, and change the URL, so that every page, every view (including popups), are properly navigable with default browser buttons.

**Comment by eggyji** [comment]
我试了几个都没问题，太棒了！
