### ISSUE TITLE
change the title "online meeting" to "URL"

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#196]
<img width="687" alt="Screenshot 2024-07-07 at 15 37 01" src="https://github.com/sociallayer-im/product-management/assets/27666814/0f8b560c-61db-477f-8b08-8a153eb9bb13">

**Comment by eggyji** [comment]
<img width="708" alt="Screenshot 2024-07-26 at 10 59 48" src="https://github.com/user-attachments/assets/97589e42-a874-4bf4-a35f-8881f4eeda62">
是否能点击链接直接打开对应网址
