### ISSUE TITLE
Crecimiento：Membership with different tracks have access to different types of events

### ISSUE THREAD

**Issue by mjmoneyiris** [sociallayer-im/product-management#212]
Aug6-Sept6
 1. QuarkID would have different types of access to different tracks. 通过 QuarkID 的不同进入权限对应关联到不同类型的 ticket，使用 ticket 限制用户进入权限。展示用户拥有的不同类型的 ticket ： cowork, wellness, programming
 2. 配置 event tag：增加固定不能修改的 event tag：cowork, wellness, programming ，后台为这些 event tag 增加用户准入属性
 3. 活动创建时选择 event tag，不同 event tag 会对应不同用户参与权限
 4. 针对没有参与权限的用户在活动展示侧给予「不可参加该活动」的提示
 
 https://www.notion.so/Crecimiento-Aug6-Sept6-09be82a98c2345c19060db810b36e1bf?pvs=4

**Comment by mjmoneyiris** [comment]
@nicosxt  @jiangplus  看一下第 2、3 点我们是否需要这么做

**Comment by nicosxt** [comment]
我觉得可以这么做

**Comment by mjmoneyiris** [comment]
设计稿已完成https://www.figma.com/design/SJQGvLw5RuN2xadroJ1i7j/%E6%B4%BB%E5%8A%A8%E5%85%A5%E5%8F%A3web?node-id=7463-5846
