### ISSUE TITLE
[bug] pop-up cities on homepage pointing to wrong groups

### ISSUE THREAD

**Issue by jiangplus** [sociallayer-im/product-management#214]
app.sola.day 首页的 pop-up city 相关链接应该指向对应 group，目前指向 https://app.sola.day/event/popupcities 这个是反直觉的。

需要创建对应的 group，然后修改 pop-up cities 的链接。

**Comment by nicosxt** [comment]
是说这里的group吗？
<img width="654" alt="Screenshot 2024-07-11 at 7 19 37 AM" src="https://github.com/sociallayer-im/product-management/assets/22283048/c739b467-2d79-44ca-baad-48ebaa617142">

**Comment by jiangplus** [comment]
对的

**Comment by nicosxt** [comment]
@jiangplus 我没办法assign一些group因为没有权限， 这个权限谁可以设置？ 比如Vitalia他有一个group但是我无法选择
<img width="527" alt="image" src="https://github.com/user-attachments/assets/69d4f8f3-baba-44a4-85b5-4b9674264354">
