### ISSUE TITLE
[feature] Events of Pop Up Cities should have a filter system

### ISSUE THREAD

**Issue by nicosxt** [sociallayer-im/product-management#216]
Would be nice if Events of Pop Up Cities have filters and people can see events chronologically or based on size, or continent.

Would also be nice to separate past, ongoing and future
<img width="1051" alt="Screenshot 2024-07-12 at 6 53 42 PM" src="https://github.com/user-attachments/assets/4ab06d44-7ae9-4d09-bc04-4d590f016088">

**Comment by mjmoneyiris** [comment]
let's discuss in some point

**Comment by nicosxt** [comment]
等我们ticket push结束之后可以再聊一下主页设计

还有可以加入的是不同的community黄页怎么设计， 然后背后数据怎么连接 @mjmoneyiris
