### ISSUE TITLE
Ticketing Improvement

### ISSUE THREAD

**Issue by jiangplus** [sociallayer-im/product-management#218]
提升票务支付的体验：
更明显的创建门票功能
更明显的看到报名按钮
支持更多的链支付 eth，polygon，op，arbitrum
不允许修改ticket的价格和收款钱包等资金的相关信息，可以隐藏ticket
支付之前检测钱包
提示使用EOA钱包接收资金，并且使用签名验证所有权，避免使用交易所地址
支付时提示用户不要关闭UI

Design 需求：

允许创建者在一个ticket设置多条链，多个收款地址

**Comment by nicosxt** [comment]
+ base network

**Comment by nicosxt** [comment]
timeline to implement payment other chains: 1hr - 1day

**Comment by mjmoneyiris** [comment]
https://www.figma.com/design/SJQGvLw5RuN2xadroJ1i7j/%E6%B4%BB%E5%8A%A8%E5%85%A5%E5%8F%A3web?node-id=7546-130717&t=wPsPcioAOviKRwlJ-4
设计中，已完成更多链的支付
