### ISSUE TITLE
nodejs api for sign-in with ethereum

### ISSUE THREAD

**Issue by jiangplus** [sociallayer-im/product-management#225]
开发基于nodejs/deno服务，进行以太坊登录的验证

输入数据信息 message，signature，返回 boolean

参考：

https://github.com/spruceid/siwe-quickstart/tree/main/02_backend

**Comment by Cupnfish** [comment]
@jiangplus 

这个需求的实现基本完成，但有几个细节需要确认：

1. **siweMessage验证**：我们是否要限制特定的域名（比如mobit.app）才能返回true？

2. **时间参数验证**：对于`issuedAt`等参数，是否要验证当前时间必须在5分钟内？超出这个时间范围就不通过？

3. **前端App的服务**：具体是要给哪个前端应用？有没有对应的origin设置要求？

等你回复，方便进一步调整。

谢谢！

**Comment by jiangplus** [comment]
nonce 和域名作为一个参数返回吧，backend 自己判断用在什么域名
可以有15分钟时间限制

**Comment by Cupnfish** [comment]
https://github.com/sociallayer-im/verify

**Comment by Cupnfish** [comment]
https://siwe-verify.deno.dev/nonce
