### ISSUE TITLE
venue availability override setting ui

### ISSUE THREAD

**Issue by jiangplus** [sociallayer-im/product-management#227]
目前venue已经有start date，end date和每周的每一天可用时间的设置；
在这基础上，用户经常要求屏蔽某些天，或者修改当天的可用时间，
设计便捷的修改UI提供此功能，类似cal.com的override，
另外建议提供一个venue的日历，显示可用时间，类似airbnb的可预订日期，供管理员参考。

**Comment by mjmoneyiris** [comment]
https://www.figma.com/design/SJQGvLw5RuN2xadroJ1i7j/%E6%B4%BB%E5%8A%A8%E5%85%A5%E5%8F%A3web?node-id=7713-5643&t=JmVieldqtKTL38Zd-4 设计稿已完成
