### ISSUE TITLE
adding venue by geo location not working

### ISSUE THREAD

**Issue by vvorski** [sociallayer-im/product-management#232]
Even though the prompt says we can input geomarker, does not work if there is a **space between the numbers**

so this works: 39.068896,-9.176794
but this does not: 39.068896, -9.176794

_because cut&paste from google maps includes the space this is quite confusing_

also space before or after the numbers breaks it... 
recommend: just strip all white-space before, after, inside the numbers

what happens: trying to input geo marker says "no result" and doesn't let me save the venue

what I expected: puts point on the map and allows me 
![image](https://github.com/user-attachments/assets/d6b49347-8745-4ca9-9c8c-2c1bebc2ae9d)

**Comment by nicosxt** [comment]
@qieman 这个可以把坐标输入进去然后显示地址吗
