### ISSUE TITLE
[Feature, Goal, GoT] Improve Map feature so it's more useful, especially on Mobile

### ISSUE THREAD

**Issue by nicosxt** [sociallayer-im/product-management#234]
Ideas:

- how can we display events in a less clustered manner? Instead of having all events displayed all time, maybe we display only when a marker is selected
- how can we make 'create a marker' easier, more intuitive and obvious?
- can we integrate external navigation service, so user can click on a marker and open it in google/apple 3rd party navigation services? (this would be VERY helpful)

**Comment by nicosxt** [comment]
+ from @jiangplus 支持多选标签

**Comment by jiangplus** [comment]
在地图显示活动报名人数/checkin 人数

**Comment by nicosxt** [comment]
- map功能应该显示： 3小时， 一天， 一周

**Comment by nicosxt** [comment]
- 命名修改： event是default 或者 official， 然后marker是custom 或者 community
- 打开之后default不要看到所有event
- 想办法把all markers里面加入venue list
- 在用户增加marker的时候也选择在这里举办event （需要修改权限）

**Comment by nicosxt** [comment]
建议 -- Marker 是大分类， Marker底下分布 Event Venue 和Attractions

**Comment by mjmoneyiris** [comment]
会议记录
- [ ] Marker、Event的概念需要区分（名称），并优化顶部 Tab 交互
- [ ] Event 增加筛选：默认显示当天、3天、未来一周、all events、指定日期等
- [ ] Map需要提供缩略展示效果以，缩小时缩略，放大时完整展示
- [ ] Marker创建流程优化，灵活、实时发布、轻量
- [ ] marker 增加 「venue」 tag
- [ ] marker 需要教育（optional）
- [ ] 批量加marker（csv.）
- [ ] event 增加xx人报名
- [ ] 移动端需要跳转到google地图
