### ISSUE TITLE
filter by venue - CRITICAL for GoT

### ISSUE THREAD

**Issue by vvorski** [sociallayer-im/product-management#236]
Currently see no way to filter by venue: https://app.sola.day/event/the-gathering/schedule?date=2024-09-09

We can filter by tag, but not venue...

This makes it hard to see what's going on around, also makes it impossible for a camp to share their programme.

Would love to have a venue filter on these views:
https://app.sola.day/event/the-gathering  - **highest priority**
https://app.sola.day/event/the-gathering/schedule?date=2024-09-09
https://app.sola.day/event/the-gathering/calendar?date=2024-09-09&view=month

**Comment by jiangplus** [comment]
Thanks for your feedback! We will implement this feature soon.
