### ISSUE TITLE
[Summer of Protocol] Requirements

### ISSUE THREAD

**Issue by jiangplus** [sociallayer-im/product-management#240]
group: https://app.sola.day/event/sopsymposium

see the order in which people RSVP for an event, Like can get a list of sign ups sorted by time
查看用户 RSVP 的时间，并且根据注册时间排序

calendar embed function code
需要嵌入 calendar view 的代码

events moved to the Featured carousel
将 group 放在sola首页，popup city 和 community 增加显示数量

Would like for users to only be able to create events between Sept. 27 at 14:00 UTC to Sept. 29 at 22:00 UTC, when non-manager users create an event, that event must occur only between *September 27 at 16:00 UTC* and *September 29 at 22:00 UTC*
限制活动的发生时间

延后实现：
If I create a badge, can people send it to each other
让徽章可以被社区成员互相发送

**Comment by jiangplus** [comment]
Is there a way for event times to be automatically localized? e.g. I create an event for 20:00 on GMT-4 time -> when a user in Seattle looks at the event, it would show 17:00. If not, is there a way to set event times in UTC?

使用 UTC 时间

**Comment by qieman** [comment]
schedule嵌入代码： 
```
<iframe src="https://www.sola.day/iframe/schedule?date=2024-09-02&group=edgeesmeralda" height="500" width="100%"></iframe>

```
calendar嵌入代码： 
```
<iframe src="https://www.sola.day/iframe/calendar?date=2024-09-02&group=edgeesmeralda" height="500" width="100%"></iframe>

```
