### ISSUE TITLE
Lovepunks

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#253]
lovepunks 的page要和 auraverse的完全同步，包括他们的venue也需要可以互相选择（好像确实就是一个page放在两个domain...）
https://app.sola.day/event/auraverse
https://app.sola.day/event/lovepunks

啊 然后lovepunks这个group name要改成lovepunkschiangmai

**Comment by eggyji** [comment]
另外lovepunks邀请我们去参加他们的活动，可以去聊一聊我们的产品
