### ISSUE TITLE
ZuThailand

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#254]

**Comment by jiangplus** [comment]
1. Create event
    a. 打通授权SDK：https://spec.sending.me/oauth-api/#sendingme-step-for-authorizing-the-app
    b. SendingMe提供一个钱包地址的列表查询API
2. 查询event
    a. Social Layer这边提供所有可用于筛选的字段，groupid，创建一个key
    b. Social Layer这边提供置顶的API

**Comment by penguinmei** [comment]
curl -X GET \
  https://hs-alpha.sending.me/_api/client/r0/zuzalu/check_wallet/0xcdb08036e15e338999d8f6a5655c0b2c7768c88e

测试环境SendingMe查询一个钱包地址是否是白名单
返回一个字段result 布尔 true代表是白名单用户

**Comment by penguinmei** [comment]
curl -X GET \
  https://hs-alpha.sending.me/_api/client/r0/zuzalu/check_wallet/0xcdb08036e15e338999d8f6a5655c0b2c7768c88e

测试环境SendingMe查询一个钱包地址是否是白名单
