### ISSUE TITLE
Edge City Lannna

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#255]
1) If a **new event is created**, is there any way **for managers to get notifications** of it?
2) Could we include **descriptions for the AV sections** similar to what we can do for the room sections?
        we can add these ourselves right in the description of the venues？
        have a **config file** 
3) Is there a way to add **a notification that anything planned less than 24 hours** in advance that there is a notification that goes up about the **type of support**?

总结上面1，3 点是考虑到一些场地管理者需要提前知晓场地预定情况，如果场地被预定需要设备支持等等能够及时反馈，因此需要notification，建议这个notification作为弹窗给到管理员。

第2点这个其实是希望在venue setting的部分可以设置详细的可选设备，类似在venue里面设置几个可选的tag并给到一些描述，目前沟通是说先用config 文件来做

**Comment by eggyji** [comment]
关于track的需求：
Each of these people in a way should become a manager of mini internal events（我的理解就是track）
have the permissions for folks to have some private functionality for a set group（private track?）
