### ISSUE TITLE
Feature Requirement

### ISSUE THREAD

**Issue by jiangplus** [sociallayer-im/product-management#259]
最近需要改进的功能：

活动审核，批准
更改参加者状态，取消参加者
群发消息给参加者
单独发送消息给某个参加者
邀请用户参加活动（通过邮箱或用户名）
查看好友参加的活动
使签到更方便
自定义表单
参加者列表视图的优化
发布活动的创建徽章
地图导航
支付流程
允许已经绑定邮箱的用户绑定钱包，尽可能提示用户绑定邮箱
clone event
feedback 按钮

**Comment by mjmoneyiris** [comment]
更改参加者状态具体是指什么？

**Comment by mjmoneyiris** [comment]
优先级排序：
邀请用户参加活动（通过邮箱或用户名）
查看好友参加的活动
clone event
活动审核，批准
自定义表单
群发消息给参加者
群发消息给参加者
更改参加者状态，取消参加者

使签到更方便
参加者列表视图的优化
发布活动的创建徽章
地图导航
支付流程
允许已经绑定邮箱的用户绑定钱包，尽可能提示用户绑定邮箱
feedback 按钮
