### ISSUE TITLE
Telegram bot for daily event summary

### ISSUE THREAD

**Issue by jiangplus** [sociallayer-im/product-management#26]
Build a Telegram bot to fetch event from sola database and print daily event summary to the telegram group.

开发一个 Telegram 机器人，可以被群管理员添加到群组，每日早上七点发布今天可以参与的活动。
从 social layer api 获得公开的活动数据。

**Comment by Cupnfish** [comment]
[已部署](https://github.com/sociallayer-im/sola-bot/blob/dd540e4a524bb9a3cc520f05d1713ab4431832a2/main.ts)

- [ ] 测试及反馈

**Comment by jiangplus** [comment]
需要新的 daily report 文案
需要在 tg group 通过命令绑定 sola group
