### ISSUE TITLE
wallet ordering in sign-in pop-up

### ISSUE THREAD

**Issue by jiangplus** [sociallayer-im/product-management#268]
登录弹出框的钱包顺序进行调整：
Email
Ethereum Browser Wallet
Wallet Connect
Zupass
ZK Email

另外延迟判断钱包列表的时间（实现在 auth app）

**Comment by qieman** [comment]
修改了登录选项顺序: https://github.com/sociallayer-im/sola-nextjs/commit/f3090bbe1e7312834501746da825cff89d00e312
关于钱包列表偶尔无显示的问题考虑升级wagmi。
