### ISSUE TITLE
bookkeeping all pages in design

### ISSUE THREAD

**Issue by jiangplus** [sociallayer-im/product-management#40]
根据  figma 文稿创建 notion 文档，整理所有的设计页面
列出所有的页面名称，功能介绍，url 路径

可选：整理到统一 figma 文稿

**Comment by mjmoneyiris** [comment]
ok

**Comment by mjmoneyiris** [comment]
https://www.notion.so/social-layer/UI-1a48d38d66d54aee9fd37976d1d14569?pvs=4
