### ISSUE TITLE
Default Timezone for Event Space

### ISSUE THREAD

**Issue by jiangplus** [sociallayer-im/product-management#8]
允许在 Group 设置默认时区，添加设置字段，用在 event calendar view 的显示

**Comment by qieman** [comment]
1. 是否要取消掉calendar里取消；
2. Event首页的活动时区是否使用这个设置；

**Comment by qieman** [comment]
当前实现：
1. timezone 在 活动设置界面设置；
2. schedule 默认使用group timezone 展示时间
3. 创建活动时区默认是group timezone，其次是系统timezone

**Comment by jiangplus** [comment]
timezone 需要按照GMT时间顺序排列
