### ISSUE TITLE
Optimizing Event Creation Form

### ISSUE THREAD

**Issue by jiangplus** [sociallayer-im/product-management#88]
优化表单创建流程
调研Google Calendar的event创建表单方式

**Comment by mjmoneyiris** [comment]
是否需要对目前日历样式进行改动（放弃event并列排列的样式），还是新增一种创建方式，新增的话新的日历放在哪个地方？另外技术上能否实现如 Google canlender 那样框选时间、创建、移动、复制等在日历上的交互同样丝滑

**Comment by jiangplus** [comment]
调研Google Calendar的event创建表单，优化创建流程（只创建的部分）
