### ISSUE TITLE
The group invitation supports unregistered email users

### ISSUE THREAD

**Issue by qieman** [sociallayer-im/product-management#89]
1. 可以发送邀请给未注册的邮箱；
2. 邮箱用户注册后收到邀请。

**Comment by eggyji** [comment]
从edgecity邀请email用户，点击发送邀请，自动跳转成wamo的邀请二维码，点击返回后回到了wamo的group page

**Comment by mjmoneyiris** [comment]
未注册的邮箱用户收不到邮箱邀请？ @qieman

**Comment by mjmoneyiris** [comment]
> 从edgecity邀请email用户，点击发送邀请，自动跳转成wamo的邀请二维码，点击返回后回到了wamo的group page

wamo的邀请二维码是什么？这个需求的背景可以简单说一下吗？
然后这个需求是不是跟最近台湾的合作 referral system 差不多？
