### ISSUE TITLE
sola bot need to adjust the post time in different timezone

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#93]
It is weird that I was informed the whole day events in the evening...

**Comment by mjmoneyiris** [comment]
how about adjusting the post time at everyday 9:00 am in the user‘s timezone？

**Comment by Cupnfish** [comment]
> how about adjusting the post time at everyday 9:00 am in the user‘s timezone？

The message posted by that robot is subscribed to a Telegram group, and there are many people within the group. Which user's timezone is being used?

**Comment by Cupnfish** [comment]
@mjmoneyiris

**Comment by jiangplus** [comment]
We should use the timezone of the group.
@Cupnfish
