### ISSUE TITLE
text editor test by shiyu

### ISSUE THREAD

**Issue by EggyJ** [sociallayer-im/product-management#94]
1.好像没有crtl+z回退功能
2.好像只有在选中一段文字的时候才能单击超链接，弹出link窗口？通常状态下是灰色，这个功能或许变成点击link键自动填充一个带https://或者www.的前置文本会好一些（也许
3.超链接弹窗显示的Href和Tittle或许可以表达更通俗化一点？
4.发布活动后，超链接的Tittle似乎没有看到在哪里显示，当然可能也是我不了解这个功用lol
5.项目符号的编辑方式有些奇怪：无法整段从数字切换成圆点，只能单行切换；也就是说一行一旦选中了其中之一就无法切换成另一种了

**Comment by jiangplus** [comment]
超链接title应该默认是用户选中的文本，改称text吧，目前的实现方式需要修改

比如 [Google](https://google.com), text 是 Google，link 是 https://google.com
href 改成 link

**Comment by qieman** [comment]
> 5.项目符号的编辑方式有些奇怪：无法整段从数字切换成圆点，只能单行切换；也就是说一行一旦选中了其中之一就无法切换成另一种了

有序无序列表的相互转换，取消列表的指令稍微复杂，目前没实现。我看了一下luma也不能对list 进行复杂操作。
但是键盘指令，Link的逻辑修改好了。
