### ISSUE TITLE
Group invitation supports CSV file

### ISSUE THREAD

**Issue by qieman** [sociallayer-im/product-management#95]

**Comment by qieman** [comment]
已经更新到： [https://sola.day/](https://sola.day/)

**Comment by mjmoneyiris** [comment]
导入照片的功能增加 「URL」是什么原因呢，这个功能输入网址后就整个网页卡死了。
单独的 添加 url 有点没用明白：框选后点击 添加 url，输入网址和标题后，标题没有显示在外部文本上。另外，不框选文本无法直接点击 url 按钮添加链接
